version : '3.1'
services :

  backend :
    image : king0209/wordpicker-backend:1.1 


  nginx :
    image : nginx
    ports :
      - 80:80
      - 433:433
    depends_on : 
      - "backend"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx
      - ./nginx/logs:/etc/nginx/logs
