version : '3.1'
services :
  backend :
    image : wordpicker-backend:1.0 
    ports :
      - 3000:3000
  nginx :
    image : nginx
    ports :
      - 80:80
    depends_on : 
      - "backend"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx
      - ./nginx/logs:/etc/nginx/logs
