version : '3.1'
services :

  backend :
    image : king0209/wordpicker-backend:1.1 


  nginx :
    image : nginx
    ports :
      - 80:80
      - 433:433
    depends_on : 
      - "backend"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx:/etc/nginx
      - /var/log/nginx:/var/log/nginx
